version: "2"
services:
  jenkins:
    image: jenkins
    ports:
     - "8180:8080"
    volumes: 
     - ~/.docker/setup/jenkins/jenkins_home:/var/jenkins_home
    environment:
     - JENKINS_OPTS=--prefix=/jenkins
  nexus:
    image: sonatype/nexus:oss
    ports:
     - "8181:8081"
    volumes:
     - ~/.docker/setup/nexus/sonatype-work:/var/sonatype-work
    environment:
     - CONTEXT_PATH=/nexus
  nginx:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - ~/.docker/setup/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
