version: "2"
services:
  jenkins:
    image: jenkins
    ports:
     - "8080:8080"
    volumes: 
     - ../jenkins/jenkins_home:/var/jenkins_home
    environment:
     - JENKINS_OPTS=--prefix=/jenkins
  nexus:
    image: sonatype/nexus:oss
    ports:
     - "8081:8081"
    volumes:
     - ../nexus/sonatype-work:/var/sonatype-work
    environment:
     - CONTEXT_PATH=/nexus
  nginx:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - ../nginx/nginx.conf:/etc/nginx/nginx.conf
