version: "2"
services:
  jenkins:
    image: jenkins
    ports:
     - "8080:8080"
    volumes: 
     - ../jenkins/jenkins_home:/var/jenkins_home
    environment:
     - JENKINS_OPTS=--prefix=/jenkins
  nexus:
    image: sonatype/nexus:oss
    ports:
     - "8081:8081"
    volumes:
     - ../nexus/sonatype-work:/var/sonatype-work
    environment:
     - CONTEXT_PATH=/nexus
  nginx:
    image: nginx
    ports:
     - "3334:80"
    volumes:
     - ../nginx/html:/usr/share/nginx/html
  haproxy:
    image: million12/haproxy
    ports:
     - "80:80"
    volumes:
     - ../haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg
    environment:
     - GATEWAY_IP=172.17.0.1
  elk:
    image: sebp/elk
    ports:
     - "5601:5601"
     - "9200:9200"
     - "5044:5044"
     - "5000:5000"
    volumes:
     - ../elk/kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
