version: "2"
services:
  jenkins:
    image: jenkins
    ports:
     - "8080:8080"
    volumes: 
     - ../jenkins/jenkins_home:/var/jenkins_home
    environment:
     - JENKINS_OPTS=--prefix=/jenkins
  nexus:
    image: sonatype/nexus3
    ports:
     - "8081:8081"
    volumes:
     - ../nexus/nexus-data:/nexus-data
     - ../nexus/etc/org.sonatype.nexus.cfg:/opt/sonatype/nexus/etc/org.sonatype.nexus.cfg:ro
     
  nginx:
    image: nginx
    ports:
     - "3334:80"
    volumes:
     - ../nginx/html:/usr/share/nginx/html:ro
  haproxy:
    image: million12/haproxy
    ports:
     - "80:80"
    volumes:
     - ../haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
    environment:
     - GATEWAY_IP=172.17.0.1
  elk:
    image: sebp/elk
    ports:
     - "5601:5601"
     - "9200:9200"
     - "5044:5044"
     - "5000:5000"
    volumes:
     - ../elk/kibana/config/kibana.yml:/opt/kibana/config/kibana.yml:ro
