version: "2"

volumes:
  dev-env-setup-gocd-server-volume: {}
  dev-env-setup-gocd-agent-volume: {}
  dev-env-setup-nexus-volume: {}
  
services:
  gocd-server:
    image: gocd/gocd-server:v17.8.0
    ports:
     - "8153:8153"
     - "8154:8154"
    volumes:
     - dev-env-setup-gocd-server-volume:/godata
     - dev-env-setup-gocd-server-volume:/home/go
     - ../go/server/config/cruise-config.xml:/godata/config/cruise-config.xml
     - ../go/server/config/password.properties:/godata/config/password.properties
  
  gocd-agent-updated:
    image: eciuca/gocd-agent-jdk8-maven3
    links:
     - gocd-server:go-server
     - nexus:nexus
    volumes:
     - dev-env-setup-gocd-agent-volume:/godata
     - /var/run/docker.sock:/var/run/docker.sock
     - ../go/agent/settings.xml:/home/go/.m2/settings.xml
    environment:
     - GO_SERVER_URL=https://gocd-server:8154/go
     - AGENT_AUTO_REGISTER_KEY=392ed31e-136e-4d5f-a4d7-d5a4f0cefc21
     - AGENT_AUTO_REGISTER_RESOURCES=java
     - AGENT_AUTO_REGISTER_ENVIRONMENTS=Development
     - AGENT_AUTO_REGISTER_HOSTNAME=Agent01

  nexus:
    image: sonatype/nexus3:3.5.0
    ports:
     - "8081:8081"
     - "8444:8444"
    volumes:
     - dev-env-setup-nexus-volume:/nexus-data
     - ../nexus/etc/nexus.properties:/nexus-data/etc/nexus.properties:ro

  nginx:
    image: nginx
    ports:
     - "3334:80"
    volumes:
     - ../nginx/html:/usr/share/nginx/html:ro

  haproxy:
    image: eciuca/haproxy:1.7.8
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ../haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    environment:
     - GATEWAY_IP=172.18.0.1

  elk:
    image: sebp/elk:551
    ports:
     - "5601:5601"
     - "9200:9200"
     - "5044:5044"
     - "5000:5000"
     - "12201:12201/udp"
    volumes:
     - ../elk/kibana/config/kibana.yml:/opt/kibana/config/kibana.yml:ro
     - ../elk/logstash/03-gelf-input.conf:/etc/logstash/conf.d/03-gelf-input.conf:ro
     - ../elk/logstash/12-dropwizard.conf:/etc/logstash/conf.d/12-dropwizard.conf:ro
     - ../elk/logstash/30-output.conf:/etc/logstash/conf.d/30-output.conf:ro
